name: build-and-test
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cc: [gcc, clang]
        steps:
            - name: Install dependencies
              run: sudo apt-get install -y --no-install-recommends ${{ matrix.cc }} bison autoconf autogen libgcrypt20-dev libgnutls28-dev libsqlite3-dev libpq-dev libmysqlclient-dev python3-dev libjson-c-dev libxml2-dev zlib1g-dev
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Generate build files
              working-directory: src
              run: ./autogen.sh
            - name: Configure build
              working-directory: src
              shell: sh
              run: ./configure --enable-use-ipv6 --enable-use-mccp --enable-use-json --enable-use-pcre
                               --enable-use-mysql --enable-use-pgsql --enable-use-sqlite
                               --enable-use-xml --enable-use-tls  --enable-use-gcrypt --enable-use-python
                               --enable-malloc-trace --enable-malloc-lpc-trace  --enable-dynamic-costs
                               --enable-eval-cost-trace --enable-trace-code
                               EXTRA_CFLAGS="-DINSIDE_TRAVIS -Werror ${{ matrix.cc == 'gcc' && '-Wno-unused-result' || '' }}" CC=${{ matrix.cc }}
            - name: Build driver
              working-directory: src
              run: make
            - name: Run tests
              working-directory: test
              shell: sh
              run: ./run.sh
